### ISSUE TITLE
java.lang.RuntimeException: Unable to create test class 'eu.luminis.elastic.cluster.ClusterServiceTestIT'

### ISSUE THREAD

**Issue by magaton** [luminis-ams/elastic-rest-spring-wrapper#12]
When executing mvn clean install

java.lang.RuntimeException: Unable to create test class 'eu.luminis.elastic.cluster.ClusterServiceTestIT'

The solution is to rename ClusterServiceTestIT to ClusterServiceIT

**Comment by magaton** [comment]
a mystery, I cannot reproduce it any more. Scrolled back to the original error message, for the record. Closing since not able to reproduce.

> [ERROR]
 Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test (default) on project elastic-rest-spring-wrapper: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test failed: There was an error in the forked process
[ERROR] java.lang.RuntimeException: Unable to create test class 'eu.luminis.elastic.cluster.ClusterServiceTestIT'
[ERROR] 	at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:135)
[ERROR] 	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:95)
[ERROR] 	at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:222)
[ERROR] 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:107)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: java.lang.ClassNotFoundException: eu.luminis.elastic.cluster.ClusterServiceTestIT
[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] 	at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
[ERROR] 	... 6 more
